DESIGN=Top_Level
DESDIR=C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\Custom Core from HDL\IGL2_MiV_FreeRTOS_Demo_Custom_Core\designer\Top_Level
TARGET_DIR=C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\Custom Core from HDL\IGL2_MiV_FreeRTOS_Demo_Custom_Core\designer\Top_Level
FAM=IGLOO2
DIE=PA4MGL2500_N
PACKAGE=vf256
PINRPT_BY_NAME=1
PINRPT_BY_NUMBER=1
BANK_REPORT=1
IOREG_REPORT=1
