Design Entry;HDL Check||(null)||Checking HDL syntax of 'config_sccb.v'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Syntax checking is successful||(null);(null)||(null);(null)
HelpInfo,C:\Microsemi\Libero_SoC_v12.3\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v12.3\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis||(null)||Error: Component(s) 'sccb_design' needs to be generated before running synthesis||(null);(null)||(null);(null)
