onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb/done
add wave -noupdate /tb/pwdn
add wave -noupdate /tb/rstn
add wave -noupdate /tb/sioc
add wave -noupdate /tb/siod
add wave -noupdate /tb/xclk
add wave -noupdate -divider top
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/SYSCLK_PERIOD
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/rst
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/clk
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/ov7670_sioc
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/ov7670_siod
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/ov7670_rst_n
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/ov7670_pwdn
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/ov7670_xclk
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/done
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/sw0_test_cmd
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/btnr_test_1p
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/sw56_regs
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/resend
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/sdat_on
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/sdat_out
add wave -noupdate -divider controller
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/rst
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/clk
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/test_mode
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/test_send
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/sw_regs
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/resend
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/done
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/sclk
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/sdat_on
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/sdat_out
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/ov7670_rst_n
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/ov7670_clk
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/ov7670_pwdn
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/start_tx
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/sccb_ready
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/id
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/addr
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/data_wr
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/finish_tx
add wave -noupdate -divider sccb
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/rst
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/clk
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/start_tx
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/id
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/addr
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/data_wr
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/ready
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/finish_tx
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/sclk
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/sdat_on
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/sdat_out
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/send_rg
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/cnt_sclk_div4
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/sclk_div4_end
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/cnt_4sclk
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/sclk_end
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/cnt_phases
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/new_phase
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/phases_end
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/ready_aux
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/pr_sccb_st
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/nx_sccb_st
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/send_data
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/cnt_8bits
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/cnt_8bits_end
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/save_indata
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_sccb/clr_datarg
add wave -noupdate -divider reg
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/rst
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/clk
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/test_mode
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/test_send
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/sw_regs
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/resend
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/sccb_ready
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/start_tx
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/done
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/id
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/addr
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/data_wr
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/ov7670_rst_n
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/ov7670_clk
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/ov7670_pwdn
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/cnt_cam_clk
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/cnt_reg
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/alltx_done
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/cam_rst_n
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/start_tx_aux
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/cnt300ms
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/end300ms
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/ena_cnt300ms
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/addr_aux
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/reg_i
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/pr_ctrl_st
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/nx_ctrl_st
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/sw_regs_st
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/sw_regs_change
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/reg_00
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/reg_01
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/reg_10
add wave -noupdate /tb/sccb_desgin_0/top_ov7670_0/controller/i_regs/reg_11
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {118228346457 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ms
update
WaveRestoreZoom {0 fs} {420 us}
