onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /testbench/rst
add wave -noupdate /testbench/clk
add wave -noupdate /testbench/sioc
add wave -noupdate /testbench/siod
add wave -noupdate /testbench/cam_rstn
add wave -noupdate /testbench/pwdn
add wave -noupdate /testbench/led
add wave -noupdate /testbench/xclk
add wave -noupdate -divider top
add wave -noupdate -radix unsigned /testbench/sccb_test_0/top_ov7670_0/SYSCLK_PERIOD
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/rst
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/clk
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/ov7670_sioc
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/ov7670_siod
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/ov7670_rst_n
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/ov7670_pwdn
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/ov7670_xclk
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/done
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/sw0_test_cmd
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/btnr_test_1p
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/sw56_regs
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/resend
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/sdat_on
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/sdat_out
add wave -noupdate -divider controller
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/rst
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/clk
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/test_mode
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/test_send
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/sw_regs
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/resend
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/done
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/sclk
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/sdat_on
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/sdat_out
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/ov7670_rst_n
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/ov7670_clk
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/ov7670_pwdn
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/start_tx
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/sccb_ready
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/id
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/addr
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/data_wr
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/finish_tx
add wave -noupdate -divider sccb
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/c_off
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/c_on
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/c_clk_period
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/c_sclk_period_div4
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/c_sclk_div4_endcnt
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/c_nb_cnt_sclk_div4
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/IDLE_ST
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/INIT_SEQ_ST
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/SEND_BYTE_ST
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/DNTC_ST
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/END_SEQ_ST
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/rst
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/clk
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/start_tx
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/id
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/addr
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/data_wr
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/ready
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/finish_tx
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/sclk
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/sdat_on
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/sdat_out
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/send_rg
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/cnt_sclk_div4
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/sclk_div4_end
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/cnt_4sclk
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/sclk_end
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/cnt_phases
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/new_phase
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/phases_end
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/ready_aux
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/pr_sccb_st
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/nx_sccb_st
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/send_data
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/cnt_8bits
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/cnt_8bits_end
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/save_indata
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_sccb/clr_datarg
add wave -noupdate -divider reg
add wave -noupdate -radix unsigned /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/c_end300ms
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/c_id_write
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/RSTCAM_ST
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/WAIT_RSTCAM_ST
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/WAIT_ST
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/WRITE_REG_ST
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/DONE_ST
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/rst
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/clk
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/test_mode
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/test_send
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/sw_regs
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/resend
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/sccb_ready
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/start_tx
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/done
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/id
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/addr
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/data_wr
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/ov7670_rst_n
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/ov7670_clk
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/ov7670_pwdn
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/cnt_cam_clk
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/cnt_reg
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/alltx_done
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/cam_rst_n
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/start_tx_aux
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/cnt300ms
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/end300ms
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/ena_cnt300ms
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/addr_aux
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/reg_i
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/pr_ctrl_st
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/nx_ctrl_st
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/sw_regs_st
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/sw_regs_change
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/reg_00
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/reg_01
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/reg_10
add wave -noupdate /testbench/sccb_test_0/top_ov7670_0/controller/i_regs/reg_11
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {8486078886311 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 69
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ms
update
WaveRestoreZoom {0 fs} {39222737819026 fs}
