quietly set ACTELLIBNAME IGLOO2
quietly set PROJECT_DIR "C:/Users/cheec/Desktop/Master/Creative-Eval-Board/IGL2_MiV_FreeRTOS_Demo/FPGA Design/IGL2_MiV_FreeRTOS_Demo_Custom_Core"
source "${PROJECT_DIR}/simulation/bfmtovec_compile.tcl";

if {[file exists presynth/_info]} {
   echo "INFO: Simulation library presynth already exists"
} else {
   file delete -force presynth 
   vlib presynth
}
vmap presynth presynth
vmap IGLOO2 "C:/Microsemi/Libero_SoC_v12.3/Designer/lib/modelsimpro/precompiled/vlog/smartfusion2"
vmap SmartFusion2 "C:/Microsemi/Libero_SoC_v12.3/Designer/lib/modelsimpro/precompiled/vlog/smartfusion2"
vmap COREAHBLITE_LIB "../component/Actel/DirectCore/CoreAHBLite/5.2.100/mti/user_vlog/COREAHBLITE_LIB"
vcom -work COREAHBLITE_LIB -force_refresh
vlog -work COREAHBLITE_LIB -force_refresh
if {[file exists COREAHBTOAPB3_LIB/_info]} {
   echo "INFO: Simulation library COREAHBTOAPB3_LIB already exists"
} else {
   file delete -force COREAHBTOAPB3_LIB 
   vlib COREAHBTOAPB3_LIB
}
vmap COREAHBTOAPB3_LIB "COREAHBTOAPB3_LIB"
if {[file exists COREAPB3_LIB/_info]} {
   echo "INFO: Simulation library COREAPB3_LIB already exists"
} else {
   file delete -force COREAPB3_LIB 
   vlib COREAPB3_LIB
}
vmap COREAPB3_LIB "COREAPB3_LIB"
if {[file exists COREJTAGDEBUG_LIB/_info]} {
   echo "INFO: Simulation library COREJTAGDEBUG_LIB already exists"
} else {
   file delete -force COREJTAGDEBUG_LIB 
   vlib COREJTAGDEBUG_LIB
}
vmap COREJTAGDEBUG_LIB "COREJTAGDEBUG_LIB"
if {[file exists CORETIMER_LIB/_info]} {
   echo "INFO: Simulation library CORETIMER_LIB already exists"
} else {
   file delete -force CORETIMER_LIB 
   vlib CORETIMER_LIB
}
vmap CORETIMER_LIB "CORETIMER_LIB"
if {[file exists MIRSLV2MIRMSTRBRIDGE_AHB_LIB/_info]} {
   echo "INFO: Simulation library MIRSLV2MIRMSTRBRIDGE_AHB_LIB already exists"
} else {
   file delete -force MIRSLV2MIRMSTRBRIDGE_AHB_LIB 
   vlib MIRSLV2MIRMSTRBRIDGE_AHB_LIB
}
vmap MIRSLV2MIRMSTRBRIDGE_AHB_LIB "MIRSLV2MIRMSTRBRIDGE_AHB_LIB"

vlog -vlog01compat -work COREAHBLITE_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vlog/core/coreahblite_slavearbiter.v"
vlog -vlog01compat -work COREAHBLITE_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vlog/core/coreahblite_slavestage.v"
vlog -vlog01compat -work COREAHBLITE_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vlog/core/coreahblite_defaultslavesm.v"
vlog -vlog01compat -work COREAHBLITE_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vlog/core/coreahblite_addrdec.v"
vlog -vlog01compat -work COREAHBLITE_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vlog/core/coreahblite_masterstage.v"
vlog -vlog01compat -work COREAHBLITE_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vlog/core/coreahblite_matrix4x16.v"
vlog -vlog01compat -work COREAHBLITE_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vlog/core/coreahblite.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/AHB_MEM/AHB_MEM.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/AHB_MMIO/AHB_MMIO.v"
vlog -vlog01compat -work MIRSLV2MIRMSTRBRIDGE_AHB_LIB "${PROJECT_DIR}/component/USER/UserCore/MIRSLV2MIRMSTRBRIDGE_AHB/1.0.3/rtl/core/mirslv2mirmstrbridge_ahb.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/AHB_Slave2MasterBridge/AHB_Slave2MasterBridge.v"
vlog -vlog01compat -work COREAHBTOAPB3_LIB "${PROJECT_DIR}/component/Actel/DirectCore/COREAHBTOAPB3/3.1.100/rtl/vlog/core/coreahbtoapb3_ahbtoapbsm.v"
vlog -vlog01compat -work COREAHBTOAPB3_LIB "${PROJECT_DIR}/component/Actel/DirectCore/COREAHBTOAPB3/3.1.100/rtl/vlog/core/coreahbtoapb3_apbaddrdata.v"
vlog -vlog01compat -work COREAHBTOAPB3_LIB "${PROJECT_DIR}/component/Actel/DirectCore/COREAHBTOAPB3/3.1.100/rtl/vlog/core/coreahbtoapb3_penablescheduler.v"
vlog -vlog01compat -work COREAHBTOAPB3_LIB "${PROJECT_DIR}/component/Actel/DirectCore/COREAHBTOAPB3/3.1.100/rtl/vlog/core/coreahbtoapb3.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/AHBtoAPB3/AHBtoAPB3.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/hdl/AND2_GATE.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/hdl/AND2_GATE_APB.v"
vlog -vlog01compat -work COREAPB3_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAPB3/4.1.100/rtl/vlog/core_obfuscated/coreapb3_muxptob3.v"
vlog -vlog01compat -work COREAPB3_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAPB3/4.1.100/rtl/vlog/core_obfuscated/coreapb3_iaddr_reg.v"
vlog -vlog01compat -work COREAPB3_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAPB3/4.1.100/rtl/vlog/core_obfuscated/coreapb3.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/APB3_Bus/APB3_Bus.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/BasicIO_Interface/BasicIO_Interface_sim.v"
vlog -vlog01compat -work COREJTAGDEBUG_LIB "${PROJECT_DIR}/component/Actel/DirectCore/COREJTAGDEBUG/3.0.100/core/corejtagdebug_ujtag_wrapper.v"
vlog -vlog01compat -work COREJTAGDEBUG_LIB "${PROJECT_DIR}/component/Actel/DirectCore/COREJTAGDEBUG/3.0.100/core/corejtagdebug_uj_jtag.v"
vlog -vlog01compat -work COREJTAGDEBUG_LIB "${PROJECT_DIR}/component/Actel/DirectCore/COREJTAGDEBUG/3.0.100/core/corejtagdebug.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/JTAG/JTAG.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MSS_SubSystem_sb/CCC_0/MSS_SubSystem_sb_CCC_0_FCCC.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MSS_SubSystem_sb/FABOSC_0/MSS_SubSystem_sb_FABOSC_0_OSC.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MSS_SubSystem_sb_HPMS/MSS_SubSystem_sb_HPMS.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/CoreConfigMaster/2.1.102/rtl/vlog/core/coreconfigmaster.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/CoreConfigP/7.1.100/rtl/vlog/core/coreconfigp.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/CoreResetP/7.1.100/rtl/vlog/core/coreresetp_pcie_hotreset.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/Actel/DirectCore/CoreResetP/7.1.100/rtl/vlog/core/coreresetp.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MSS_SubSystem_sb/MSS_SubSystem_sb.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_coreplex_local_interrupter_clint.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_capture_chain.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_capture_update_chain_1.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_capture_update_chain.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_jtag_bypass_chain.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_capture_update_chain_2.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_reset_reg.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_reset_reg_vec_w4_i15.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_jtag_state_machine.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_negative_edge_latch_2.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_negative_edge_latch.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_jtag_tap_controller.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_debug_transport_module_jtag.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_reset_reg_vec_w1_i0.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_reset_reg_vec_w2_i0.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_int_sync_crossing_source_2.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_int_xbar.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_synchronizer_shift_reg_w31_d3.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_int_xing.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlwidth_widget.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlxbar_memory_bus.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_memory_bus_mem_buses_0.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlatomic_automata_periphery_bus_slave_tlfragmenter.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlbuffer_periphery_bus_slave_tlbuffer.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_queue_1.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_queue.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlbuffer_periphery_bus_slave_tlfragmenter.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_repeater_2.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_repeater.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlfragmenter_periphery_bus_slave_tlfragmenter.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlxbar_periphery_bus.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_periphery_bus_pbus.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_reset_synchronizer_shift_reg_w1_d3_i0.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_reset_catch_and_sync_d3.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_amoalu.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_arbiter_1.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_arbiter.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_data_arrays_0_ext.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_data_arrays_0.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_dcache_data_array.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tag_array_ext.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tag_array.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlb.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_dcache_dcache.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_data_arrays_0_0_ext.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_data_arrays_0_0.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tag_array_0_ext.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tag_array_0.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_icache_icache.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_shift_queue.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlb_1.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_frontend_frontend.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_hella_cache_arbiter.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_int_sync_crossing_sink_1.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_synchronizer_shift_reg_w1_d3.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_int_sync_crossing_sink.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_int_xbar_int_xbar.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_alu.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_breakpoint_unit.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_csrfile.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_rvcexpander.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_ibuf.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_mul_div.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_plusarg_reader.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_rocket.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_queue_11.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_queue_13.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_queue_14.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_queue_15.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_queue_6.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlbuffer_system_bus.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlxbar_tl_master_xbar.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_rocket_tile.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlcache_cork_system_bus.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlfifofixer_system_bus.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_simple_lazy_module_system_bus_from_tile.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_queue_4.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_queue_5.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlbuffer_system_bus_slave_tlbuffer.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlfifofixer_system_bus_pbus_tlfifofixer.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlsplitter_system_bus_master_tlsplitter.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlwidth_widget_system_bus_slave_tlwidth_widget.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_identity_module.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlxbar_system_bus.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_system_bus_sbus.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_reset_synchronizer_shift_reg_w1_d4_i0.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_valid_sync_3.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_reset_synchronizer_shift_reg_w1_d1_i0.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_valid_sync_4.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_valid_sync_5.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_synchronizer_shift_reg_w12_d1.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_queue_sink_2.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_synchronizer_shift_reg_w54_d1.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_queue_sink_1.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_valid_sync_1.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_valid_sync_2.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_valid_sync.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_queue_source_2.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlasync_crossing_sink_dmi_xing.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tldebug_module_inner_dm_inner.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tldebug_module_inner_async_dm_inner.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_queue_source_1.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_dmito_tl_dmi2tl.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_int_sync_crossing_source.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_synchronizer_shift_reg_w42_d1.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_queue_sink.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_queue_source.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlasync_crossing_source_dm_inner.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_async_reset_reg_vec_w32_i0.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tldebug_module_outer_dm_outer.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlxbar_dmi_xbar.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tldebug_module_outer_async_dm_outer.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tldebug_module_debug.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_queue_18.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_queue_19.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlerror_error.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlfilter.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_level_gateway.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_queue_10.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlplic_plic.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_queue_16.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlto_ahb_converter.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_tlto_ahb.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb_rocket_system.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32_0/core/miv_rv32ima_l1_ahb.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/MiV_Core32/MiV_Core32.v"
vlog -vlog01compat -work CORETIMER_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreTimer/2.0.103/rtl/vlog/core/coretimer.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/Timer/Timer.v"
vlog -vlog01compat -work presynth "${PROJECT_DIR}/component/work/Top_Level/Top_Level.v"
vlog "+incdir+${PROJECT_DIR}/component/Actel/DirectCore/CoreAHBLite/5.2.100" "+incdir+${PROJECT_DIR}/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vlog/test/user" -vlog01compat -work COREAHBLITE_LIB "${PROJECT_DIR}/component/Actel/DirectCore/CoreAHBLite/5.2.100/rtl/vlog/test/user/testbench.v"

vsim -L IGLOO2 -L presynth -L COREAHBLITE_LIB -L COREAHBTOAPB3_LIB -L COREAPB3_LIB -L COREJTAGDEBUG_LIB -L CORETIMER_LIB -L MIRSLV2MIRMSTRBRIDGE_AHB_LIB  -t 1fs COREAHBLITE_LIB.testbench
add wave /testbench/*
run -all
