set_family {IGLOO2}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite_slavearbiter.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite_slavestage.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite_defaultslavesm.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite_addrdec.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite_masterstage.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite_matrix4x16.v}
read_verilog -mode verilog_2k -lib COREAHBLITE_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreAHBLite\5.2.100\rtl\vlog\core\coreahblite.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\AHB_MEM\AHB_MEM.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\AHB_MMIO\AHB_MMIO.v}
read_verilog -mode verilog_2k -lib MIRSLV2MIRMSTRBRIDGE_AHB_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\USER\UserCore\MIRSLV2MIRMSTRBRIDGE_AHB\1.0.3\rtl\core\mirslv2mirmstrbridge_ahb.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\AHB_Slave2MasterBridge\AHB_Slave2MasterBridge.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_ahbtoapbsm.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_apbaddrdata.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3_penablescheduler.v}
read_verilog -mode verilog_2k -lib COREAHBTOAPB3_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\COREAHBTOAPB3\3.1.100\rtl\vlog\core\coreahbtoapb3.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\AHBtoAPB3\AHBtoAPB3.v}
read_verilog -mode verilog_2k -lib COREAPB3_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core_obfuscated\coreapb3_muxptob3.v}
read_verilog -mode verilog_2k -lib COREAPB3_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core_obfuscated\coreapb3_iaddr_reg.v}
read_verilog -mode verilog_2k -lib COREAPB3_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreAPB3\4.1.100\rtl\vlog\core_obfuscated\coreapb3.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\APB3_Bus\APB3_Bus.v}
read_verilog -mode verilog_2k -lib COREJTAGDEBUG_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\COREJTAGDEBUG\3.0.100\core\corejtagdebug_ujtag_wrapper.v}
read_verilog -mode verilog_2k -lib COREJTAGDEBUG_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\COREJTAGDEBUG\3.0.100\core\corejtagdebug_uj_jtag.v}
read_verilog -mode verilog_2k -lib COREJTAGDEBUG_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\COREJTAGDEBUG\3.0.100\core\corejtagdebug.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\JTAG\JTAG.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MSS_SubSystem_sb\CCC_0\MSS_SubSystem_sb_CCC_0_FCCC.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MSS_SubSystem_sb\FABOSC_0\MSS_SubSystem_sb_FABOSC_0_OSC.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MSS_SubSystem_sb_HPMS\MSS_SubSystem_sb_HPMS.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreConfigMaster\2.1.102\rtl\vlog\core\coreconfigmaster.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreConfigP\7.1.100\rtl\vlog\core\coreconfigp.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreResetP\7.1.100\rtl\vlog\core\coreresetp_pcie_hotreset.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreResetP\7.1.100\rtl\vlog\core\coreresetp.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MSS_SubSystem_sb\MSS_SubSystem_sb.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_coreplex_local_interrupter_clint.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_capture_chain.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_capture_update_chain_1.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_capture_update_chain.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_jtag_bypass_chain.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_capture_update_chain_2.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_reset_reg.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_reset_reg_vec_w4_i15.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_jtag_state_machine.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_negative_edge_latch_2.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_negative_edge_latch.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_jtag_tap_controller.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_debug_transport_module_jtag.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_reset_reg_vec_w1_i0.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_reset_reg_vec_w2_i0.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_int_sync_crossing_source_2.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_int_xbar.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_synchronizer_shift_reg_w31_d3.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_int_xing.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlwidth_widget.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlxbar_memory_bus.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_memory_bus_mem_buses_0.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlatomic_automata_periphery_bus_slave_tlfragmenter.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlbuffer_periphery_bus_slave_tlbuffer.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_queue_1.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_queue.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlbuffer_periphery_bus_slave_tlfragmenter.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_repeater_2.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_repeater.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlfragmenter_periphery_bus_slave_tlfragmenter.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlxbar_periphery_bus.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_periphery_bus_pbus.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_reset_synchronizer_shift_reg_w1_d3_i0.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_reset_catch_and_sync_d3.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_amoalu.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_arbiter_1.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_arbiter.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_data_arrays_0_ext.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_data_arrays_0.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_dcache_data_array.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tag_array_ext.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tag_array.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlb.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_dcache_dcache.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_data_arrays_0_0_ext.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_data_arrays_0_0.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tag_array_0_ext.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tag_array_0.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_icache_icache.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_shift_queue.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlb_1.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_frontend_frontend.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_hella_cache_arbiter.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_int_sync_crossing_sink_1.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_synchronizer_shift_reg_w1_d3.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_int_sync_crossing_sink.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_int_xbar_int_xbar.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_alu.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_breakpoint_unit.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_csrfile.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_rvcexpander.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_ibuf.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_mul_div.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_plusarg_reader.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_rocket.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_queue_11.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_queue_13.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_queue_14.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_queue_15.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_queue_6.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlbuffer_system_bus.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlxbar_tl_master_xbar.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_rocket_tile.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlcache_cork_system_bus.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlfifofixer_system_bus.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_simple_lazy_module_system_bus_from_tile.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_queue_4.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_queue_5.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlbuffer_system_bus_slave_tlbuffer.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlfifofixer_system_bus_pbus_tlfifofixer.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlsplitter_system_bus_master_tlsplitter.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlwidth_widget_system_bus_slave_tlwidth_widget.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_identity_module.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlxbar_system_bus.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_system_bus_sbus.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_reset_synchronizer_shift_reg_w1_d4_i0.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_valid_sync_3.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_reset_synchronizer_shift_reg_w1_d1_i0.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_valid_sync_4.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_valid_sync_5.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_synchronizer_shift_reg_w12_d1.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_queue_sink_2.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_synchronizer_shift_reg_w54_d1.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_queue_sink_1.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_valid_sync_1.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_valid_sync_2.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_valid_sync.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_queue_source_2.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlasync_crossing_sink_dmi_xing.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tldebug_module_inner_dm_inner.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tldebug_module_inner_async_dm_inner.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_queue_source_1.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_dmito_tl_dmi2tl.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_int_sync_crossing_source.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_synchronizer_shift_reg_w42_d1.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_queue_sink.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_queue_source.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlasync_crossing_source_dm_inner.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_async_reset_reg_vec_w32_i0.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tldebug_module_outer_dm_outer.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlxbar_dmi_xbar.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tldebug_module_outer_async_dm_outer.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tldebug_module_debug.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_queue_18.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_queue_19.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlerror_error.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlfilter.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_level_gateway.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_queue_10.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlplic_plic.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_queue_16.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlto_ahb_converter.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_tlto_ahb.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb_rocket_system.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32_0\core\miv_rv32ima_l1_ahb.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\MiV_Core32\MiV_Core32.v}
read_verilog -mode verilog_2k -lib CORETIMER_LIB {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\Actel\DirectCore\CoreTimer\2.0.103\rtl\vlog\core\coretimer.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\Timer\Timer.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\hdl\CoreSCCB.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\hdl\CoreSCCB_APB.v}
read_verilog -mode verilog_2k {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\component\work\Top_Level\Top_Level.v}
set_top_level {Top_Level}
map_netlist
read_sdc {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\constraint\Top_Level_derived_constraints.sdc}
read_sdc {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\constraint\JTAG_tck_constraint.sdc}
check_constraints {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\constraint\synthesis_sdc_errors.log}
write_fdc {C:\Users\cheec\Desktop\Master\RISC-V_FreeRTOS_Computer_Vision\SCCB Testing\IGL2_MiV_FreeRTOS_Demo\designer\Top_Level\synthesis.fdc}
